// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtgziyngrhdpdlvryoow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0Z3ppeW5ncmhkcGRsdnJ5b293Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwOTk4ODAsImV4cCI6MjA3MTY3NTg4MH0.GejvyiLgs2MNFeWWf0XJxT5IeHafhzokuzc3D9lM6n4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});